[
    {
        "id": 4,
        "prev_answer_id": null,
        "questionnaire_type": "SQ",
        "company_id": 3,
        "financial_year_id": 6,
        "question_id": 262,
        "questionType": "trends_question",
        "answer_id": 4,
        "last_updated_by": 173,
        "update_type": "Answered",
        "auditer_id": 3,
        "audit_status": "IN_VERIFICATION",
        "generate_report": 0,
        "answer_details": {
            "id": 4,
            "financial_year_id": 6,
            "question_id": 262,
            "user_id": 173,
            "source_id": "46",
            "auditer_id": 3,
            "company_id": 3,
            "remark": null,
            "proof_document": null,
            "answered_at": "2023-10-23T10:45:41.000Z",
            "reviewd_at": null,
            "answer": "{\"from_date\":\"2023-04\",\"to_date\":\"2023-06\",\"meter_id\":\"46\",\"process\":\"2\",\"reading_value\":\"800\",\"note\":\"hhh\",\"status\":false,\"id\":123456,\"source\":\"deeeep\"}",
            "status": "IN_REVIEW",
            "zb_users.id": 173,
            "zb_users.register_company_name": "satya & company",
            "zb_users.profile_picture": null,
            "zb_users.first_name": "Litchi",
            "zb_users.last_name": "SubAd",
            "change_type": "ANSWER"
        },
        "question": {
            "id": 262,
            "industry_id": "",
            "frameworkId": "1",
            "topicId": "2",
            "kpiId": null,
            "company_id": 0,
            "questionType": "quantitative_trends",
            "is_dependent": "NO",
            "formula": null,
            "graph_applicable": "NO",
            "entity": "company",
            "readingValue": null,
            "tab_name": null,
            "uri": null,
            "heading": "formulaQestion",
            "title": "FORMULA TESTING",
            "createdAt": "2023-07-20T06:55:15.000Z",
            "updatedAt": "2023-07-20T06:55:15.000Z",
            "question_detail": [
                {
                    "id": 959,
                    "question_id": 262,
                    "option_type": "reading_value",
                    "option": "",
                    "rules": null,
                    "createdAt": "2023-07-20T06:55:15.000Z",
                    "updatedAt": "2023-07-20T06:55:15.000Z"
                }
            ]
        },
        "last_role": 3,
        "validatePermission": true
    },
    {
        "id": 3,
        "prev_answer_id": null,
        "questionnaire_type": "SQ",
        "company_id": 3,
        "financial_year_id": 6,
        "question_id": 12,
        "questionType": "tabular_question",
        "answer_id": 4,
        "last_updated_by": 173,
        "update_type": "Answered",
        "auditer_id": 3,
        "audit_status": "IN_VERIFICATION",
        "generate_report": 0,
        "answer_details": {
            "id": 4,
            "financial_year_id": 6,
            "question_id": 12,
            "user_id": 173,
            "source_id": "",
            "auditer_id": 3,
            "company_id": 3,
            "remark": null,
            "proof_document": null,
            "answered_at": "2023-10-24T07:35:54.000Z",
            "reviewd_at": null,
            "answer": "[[\"ghhcgf\"],[\"\"],[\"\"]]",
            "status": "IN_REVIEW",
            "zb_users.id": 173,
            "zb_users.register_company_name": "satya & company",
            "zb_users.profile_picture": null,
            "zb_users.first_name": "Litchi",
            "zb_users.last_name": "SubAd",
            "change_type": "ANSWER"
        },
        "question": {
            "id": 12,
            "industry_id": "",
            "frameworkId": "1",
            "topicId": "2",
            "kpiId": null,
            "company_id": 0,
            "questionType": "tabular_question",
            "is_dependent": null,
            "formula": null,
            "graph_applicable": "NO",
            "entity": "company",
            "readingValue": null,
            "tab_name": null,
            "uri": null,
            "heading": "Details of the listed entity",
            "title": "Name and contact details (telephone, email address) of the person who may be contacted in case of any queries on the BRSR report\t\t\t\t",
            "createdAt": "2023-05-24T15:35:33.000Z",
            "updatedAt": "2023-05-24T15:35:33.000Z",
            "question_detail": [
                {
                    "id": 8,
                    "question_id": 12,
                    "option_type": "row",
                    "option": "Name",
                    "rules": null,
                    "createdAt": "2023-05-24T15:35:33.000Z",
                    "updatedAt": "2023-05-24T15:35:33.000Z"
                },
                {
                    "id": 9,
                    "question_id": 12,
                    "option_type": "row",
                    "option": "Contact",
                    "rules": null,
                    "createdAt": "2023-05-24T15:35:33.000Z",
                    "updatedAt": "2023-05-24T15:35:33.000Z"
                },
                {
                    "id": 10,
                    "question_id": 12,
                    "option_type": "row",
                    "option": "E mail",
                    "rules": null,
                    "createdAt": "2023-05-24T15:35:33.000Z",
                    "updatedAt": "2023-05-24T15:35:33.000Z"
                },
                {
                    "id": 11,
                    "question_id": 12,
                    "option_type": "column",
                    "option": "Response",
                    "rules": null,
                    "createdAt": "2023-05-24T15:35:33.000Z",
                    "updatedAt": "2023-05-24T15:35:33.000Z"
                }
            ]
        },
        "last_role": 3,
        "combined_answers": {
            "0": {
                "id": 4,
                "financial_year_id": 6,
                "question_id": 12,
                "user_id": 173,
                "source_id": "",
                "auditer_id": 3,
                "company_id": 3,
                "remark": null,
                "proof_document": null,
                "answered_at": "2023-10-24T07:35:54.000Z",
                "reviewd_at": null,
                "answer": "[[\"ghhcgf\"],[\"\"],[\"\"]]",
                "status": "IN_REVIEW",
                "zb_users.id": 173,
                "zb_users.register_company_name": "satya & company",
                "zb_users.profile_picture": null,
                "zb_users.first_name": "Litchi",
                "zb_users.last_name": "SubAd",
                "change_type": "ANSWER"
            }
        },
        "validatePermission": true
    },
    {
        "id": 2,
        "prev_answer_id": null,
        "questionnaire_type": "SQ",
        "company_id": 3,
        "financial_year_id": 6,
        "question_id": 1,
        "questionType": "qualitative",
        "answer_id": 7,
        "last_updated_by": 173,
        "update_type": "Answered",
        "auditer_id": 3,
        "audit_status": "IN_VERIFICATION",
        "generate_report": 0,
        "answer_details": {
            "id": 7,
            "user_id": 173,
            "financial_year_id": 6,
            "question_id": 1,
            "auditer_id": 3,
            "answer": "hello testing",
            "proof_document": null,
            "reviewd_at": null,
            "remark": null,
            "company_id": 3,
            "question_type": "qualitative",
            "status": "IN_REVIEW",
            "questionnaire_type": "SQ",
            "answered_at": "2023-10-24T07:32:03.000Z",
            "createdAt": "2023-10-24T07:32:03.000Z",
            "updatedAt": "2023-10-24T07:32:03.000Z",
            "zb_users.id": 173,
            "zb_users.register_company_name": "satya & company",
            "zb_users.profile_picture": null,
            "zb_users.first_name": "Litchi",
            "zb_users.last_name": "SubAd"
        },
        "question": {
            "id": 1,
            "industry_id": "",
            "frameworkId": "1",
            "topicId": "2",
            "kpiId": null,
            "company_id": 0,
            "questionType": "qualitative",
            "is_dependent": "YES",
            "formula": null,
            "graph_applicable": "NO",
            "entity": "company",
            "readingValue": null,
            "tab_name": null,
            "uri": null,
            "heading": "Details of the listed entity",
            "title": "Corporate Identity Number (CIN) of the Listed Entity",
            "createdAt": "2023-05-24T15:35:32.000Z",
            "updatedAt": "2023-07-17T12:01:34.000Z",
            "question_detail": []
        },
        "last_role": 3,
        "validatePermission": true
    },
    {
        "id": 1,
        "prev_answer_id": null,
        "questionnaire_type": "SQ",
        "company_id": 3,
        "financial_year_id": 6,
        "question_id": 3,
        "questionType": "quantitative",
        "answer_id": 6,
        "last_updated_by": 173,
        "update_type": "Answered",
        "auditer_id": 3,
        "audit_status": "IN_VERIFICATION",
        "generate_report": 0,
        "answer_details": {
            "id": 6,
            "user_id": 173,
            "financial_year_id": 6,
            "question_id": 3,
            "auditer_id": 3,
            "answer": "3",
            "proof_document": null,
            "reviewd_at": null,
            "remark": null,
            "company_id": 3,
            "question_type": "quantitative",
            "status": "IN_REVIEW",
            "questionnaire_type": "SQ",
            "answered_at": "2023-10-24T07:32:03.000Z",
            "createdAt": "2023-10-24T07:32:03.000Z",
            "updatedAt": "2023-10-24T07:32:03.000Z",
            "zb_users.id": 173,
            "zb_users.register_company_name": "satya & company",
            "zb_users.profile_picture": null,
            "zb_users.first_name": "Litchi",
            "zb_users.last_name": "SubAd"
        },
        "question": {
            "id": 3,
            "industry_id": "",
            "frameworkId": "1",
            "topicId": "2",
            "kpiId": null,
            "company_id": 0,
            "questionType": "quantitative",
            "is_dependent": null,
            "formula": "Q11+Q18",
            "graph_applicable": "NO",
            "entity": "company",
            "readingValue": null,
            "tab_name": null,
            "uri": null,
            "heading": "Details of the listed entity",
            "title": "Year of incorporation",
            "createdAt": "2023-05-24T15:35:32.000Z",
            "updatedAt": "2023-05-24T15:35:32.000Z",
            "question_detail": [
                {
                    "id": 1,
                    "question_id": 3,
                    "option_type": "mcqs",
                    "option": "",
                    "rules": null,
                    "createdAt": "2023-05-24T15:35:32.000Z",
                    "updatedAt": "2023-05-24T15:35:32.000Z"
                }
            ]
        },
        "last_role": 3,
        "validatePermission": true
    }
]