const data = {
    289: "Total Diesel consumed within the operational boundary of the company",
    292: "Total LPG consumed within the operational boundary of the company",
    293: "Total Petrol consumed within the operational boundary of the company",
    294: "Total CNG consumed within the operational boundary of the company",
    295: "Total PNG consumed within the operational boundary of the company",
    391: "Total Groundwater consumption",
    392: "Total Water Bill",
    393: "Total wastewater generated",
    394: "Total Wastewater treated (STP/ETP)*",
    395: "Total treated water recycled (Flushing/CT etc)",
    396: "Water recycling/reuse percentage",
    397: "Total quantity of sludge treated",
    398: "Total quantity of sludge treated in OWC",
    399: "Total cost for STP treatment",
    400: "Total non-hazardous solid waste generated (black category general waste)",
    401: "Total non-hazardous solid waste sent to landfill (construction waste/other waste to landfill)",
    402: "Total packaging waste (Non-Plastic) generated",
    403: "Total revenue from non-plastic packaging waste",
    404: "Total plastic packaging waste generated ",
    405: "Total revenue from plastic packaging waste",
    406: "Total metal scraps disposed",
    407: "Total revenue from metal scraps",
    408: "Total food waste generated/Kitchen Waste* (Kgs)",
    409: "Total biomedical waste generated",
    410: "Total biomedical waste disposal Bill",
    411: "Total e-waste revenue",
    412: "Total e-waste generated",
    413: "Total e-waste disposed",
    414: "Total hazardous waste (spent oil/lubricants etc)",
    415: "Total battery waste recycled",
    416: "GHG emissions Scope 1",
    417: "Total Petrol Bill",
    418: "Total Diesel Bill",
    419: "Total CNG Bill",
    420: "Total PNG Bill",
    421: "GHG emissions due to consumption of Petrol",
    422: "GHG emissions due to consumption of Diesel",
    423: "GHG emissions due to consumption of CNG",
    424: "GHG emissions due to consumption of PNG",
    425: "Emissions due to GRID electricity",
    426: "Electricity Power plant (Captive Power Plant - Natural Gas)",
    427: "Emissions due to Electricity Power plant (Captive Power Plant - Natural Gas)",
    428: "Electricity consumption through DG",
    429: "Total electricity consumption from Renewable energy (via PPA)",
    430: "Total electricity consumption from Renewable energy (rooftop solar)",
    431: "Total Electricity Bill",
    432: "Males out of total employees",
    433: "Females out of total employees",
    434: "Employees less than 30 years of age (%) (%)",
    435: "Employees between 30-50 years of age (%) (%)",
    436: "Employees more than 50 years of age (%) (%)",
    437: "Manpower turnover rate",
    438: "Average training hours per employee",
    439: "Mock drills",
    440: "Fire Safety Audits",
    441: "Safety Trainings",
    442: "Safety Committee Meetings",
    443: "Number of Fatalities",
    444: "High consequence injuries",
    445: "Recordable injuries",
    446: "Recordable work-related ill-health cases",
    448: "Occupancy",
    449: "GHG emissions due to consumption of LPG",
    450: "Total LPG Bill",
    468: "Total electricity consumption (GRID electricity)",
    469: "Total Tanker Water Consumption",
    470: "Total water consumption limit as per Consent to Operate",
    471: "Total groundwater consumption limit as per CGWA NOC",
    472: "Number of deviations reported in terms of water consumption with respect to CTO limit",
    473: "Number of deviations reported in terms of water consumption with respect to CGWA limit",
    474: "Total surface water consumption (this includes municipal supply water)",
    475: "Zero Liquid Discharge (ZLD)",
    476: "Do you have hazardous waste generation?",
    477: "Total waste reused",
    478: "Total waste recycled",
    479: "Total packaging waste (Non-Plastic) recycled",
    480: "Total packaging waste (Plastic) recycled",
    481: "Total biomedical waste recycled",
    482: "Total e-waste recycled",
    483: "Total number of packaging used",
    484: "Number of packaging material with sustainable materials",
    485: "How many deviations observed in ambient air quality report appeared",
    486: "Total number of significant deviations reported in the environmental monitoring reports with respect to applicable regulatory standard or permits",
    487: "Number of deviations observed in ambient air quality report",
    488: "Number of deviations observed in ambient noise level report",
    489: "Number of deviations observed in air emissions reports (stacks) appeared",
    490: "Number of deviations observed in air emissions reports (Diesel Generator)",
    491: "Number of deviations observed in drinking water quality report",
    492: "Number of deviations observed in treated wastewater quality report",
    493: "Number of deviations observed in groundwater quality report for waste sector",
    494: "Number of deviations observed in soil quality report for waste sector",
    495: "Total Furnace oil (FO) consumed within the operational boundary of the company",
    496: "Total GHG emissions due to consumption of FO",
    497: "Total Coal consumed within the operational boundary of the company",
    498: "GHG emissions due to consumption of Coal",
    499: "Briquette consumed within the operational boundary of the company",
    500: "GHG emissions due to consumption of briquette",
    501: "New hires by Gender Male",
    502: "New hires by Gender Female",
    503: "New hires by age groups (30-50)",
    504: "New hires by age groups (>50)",
    505: "Average training hours per employee by gender (in Hours/Number of employees)",
    506: "Number of Environmental Incidents",
    507: "Testing and Certification of Lift",
    510: "Are you using sustainable packaging material",
    511: "Total recycled waste revenue (plastic + non-plastic)",
    512: "Nitrous Oxide (N₂O)",
    513: "Carbon Dioxide (CO₂)",
    514: "Entonox",
    515: "Desflurane",
    516: "Isoflurane",
    517: "Sevoflurane",
    518: "R 134 A",
    519: "R-22",
    520: "R-407C",
    521: "R-32",
    522: "R-410A",
    523: "SEVITRUE INHALATION 250 ML ( SEVOFL)",
    524: "SEVOFLURANE anaesthetic Inhaler 250 ML",
    525: "SUPRANE anaesthetic Inhaler 240 ML",
    526: "SEVORANE anaesthetic Inhaler 250 ML",
    527: "Total Water consumption (Ground water+municipal supply water+tanker water)",
    528: "Total Electrical Consumption",
    529: "Greenhouse Gas Emissions Scope-1",
    530: "Greenhouse Gas Emissions Scope-2"
  };
  